SELECT   CD_UNID_INT
        ,DS_UNID_INT
        ,CD_LEITO
        ,DS_LEITO
        ,CD_ATENDIMENTO
        ,HR_ATENDIMENTO
        ,CD_PACIENTE
        ,NM_PACIENTE
        ,DT_NASCIMENTO

FROM (
SELECT  UNID_INT.CD_UNID_INT
       ,UNID_INT.DS_UNID_INT
       ,LEITO.CD_LEITO
       ,LEITO.DS_LEITO
       ,ATENDIME.CD_ATENDIMENTO
       ,ATENDIME.HR_ATENDIMENTO
       ,ATENDIME.CD_PACIENTE
       ,SUBSTR(PACIENTE.NM_PACIENTE, 1 , (INSTR(PACIENTE.NM_PACIENTE, ' ' , 1, 1) +1 ))||'.' AS NM_PACIENTE
       ,PACIENTE.DT_NASCIMENTO
FROM ATENDIME
    ,LEITO
    ,UNID_INT
    ,PACIENTE
WHERE ATENDIME.CD_LEITO = LEITO.CD_LEITO
AND   LEITO.CD_UNID_INT = UNID_INT.CD_UNID_INT
AND   ATENDIME.CD_PACIENTE = PACIENTE.CD_PACIENTE
AND   ATENDIME.DT_ALTA IS NULL
AND   ATENDIME.TP_ATENDIMENTO = 'I'
--AND   UNID_INT.CD_UNID_INT = 37
)