--- query painel original sabará, Adaptada por Geovanna
--- TEMPO REAL CADASTRO
 
SELECT 
 COR.DS_REFERENCIA,
 FILA.DS_FILA FILA,
 count (*) AS EM_ESPERA_CADASTRO,    
 SUBSTR( (CAST(DH_PRE_ATENDIMENTO_FIM  AS TIMESTAMP) - CAST( SYSDATE AS TIMESTAMP) ),12,8 ) MAIOR_TEMPO_CADASTRO
 

FROM TRIAGEM_ATENDIMENTO A
INNER JOIN ESPECIALID B ON A.CD_ESPECIALID=B.CD_ESPECIALID
INNER JOIN COR_REFERENCIA COR ON A.CD_COR_REFERENCIA = COR.CD_COR_REFERENCIA
INNER JOIN FILA_SENHA FILA ON A.CD_FILA_SENHA = FILA.CD_FILA_SENHA 
WHERE A.DH_PRE_ATENDIMENTO_FIM is NOT NULL 
AND A.CD_FILA_SENHA IN (1,8)
AND A.NM_PACIENTE IS NOT NULL 
AND B.CD_ESPECIALID=36
AND A.cd_classificacao is not null 
AND A.cd_atendimento is null
AND A.DS_OBSERVACAO_REMOVIDO IS NULL
and a.cd_usuario_removeu IS NULL
AND TRUNC(A.DH_PRE_ATENDIMENTO_FIM)=to_date(sysdate, 'dd/mm/rrrr')
GROUP BY A.CD_COR_REFERENCIA, COR.DS_REFERENCIA,FILA.DS_FILA,DH_PRE_ATENDIMENTO_FIM     


