--- -query painel original sabará, Adaptada por Geovanna
---  MAIOR TEMPO CADASTRO 

SELECT
'CADASTRO - DIRECIONADO' TIPO,
 SubStr(CAST(SYSDATE AS TIMESTAMP) - Max(CAST(DH_PRE_ATENDIMENTO_FIM AS TIMESTAMP)), 11,9) MAIOR_TEMPO_CADASTRO ,
 Count(*) EM_ESPERA_ATENDIMENTO


FROM TRIAGEM_ATENDIMENTO A
INNER JOIN ESPECIALID B
ON A.CD_ESPECIALID = B.CD_ESPECIALID
WHERE A.DH_PRE_ATENDIMENTO_FIM is NOT NULL
AND A.NM_PACIENTE IS NOT NULL
AND A.CD_FILA_SENHA = 1
AND B.CD_ESPECIALID = 36
AND A.cd_classificacao is not null
AND A.cd_atendimento is null
AND A.DS_OBSERVACAO_REMOVIDO IS NULL
and a.cd_usuario_removeu  IS NULL
AND TRUNC(A.DH_PRE_ATENDIMENTO_FIM) =
to_date(sysdate, 'dd/mm/rrrr')


UNION

SELECT
'CADASTRO - TRADICIONAL' TIPO,
 SubStr(CAST(SYSDATE AS TIMESTAMP) - Max(CAST(DH_PRE_ATENDIMENTO_FIM AS TIMESTAMP)), 11,9) MAIOR_TEMPO_CADASTRO,
 Count(*) EM_ESPERA_ATENDIMENTO


FROM TRIAGEM_ATENDIMENTO A
INNER JOIN ESPECIALID B
ON A.CD_ESPECIALID = B.CD_ESPECIALID
WHERE A.DH_PRE_ATENDIMENTO_FIM is NOT NULL
AND A.NM_PACIENTE IS NOT NULL
AND A.CD_FILA_SENHA = 8
AND B.CD_ESPECIALID = 36
AND A.cd_classificacao is not null
AND A.cd_atendimento is null
AND A.DS_OBSERVACAO_REMOVIDO IS NULL
and a.cd_usuario_removeu  IS NULL
AND TRUNC(A.DH_PRE_ATENDIMENTO_FIM) =
to_date(sysdate, 'dd/mm/rrrr')




