-- AJUSTADA POR ANDRA EM 18/05/22

SELECT 'TRIAGEM - TRADICIONAL' TIPO 
      , QTD_TRIAGEM
      , Max (tempo) MAIOR_TEMPO_ESP  
FROM (
SELECT SUBSTR( (CAST(DH_PRE_ATENDIMENTO  AS TIMESTAMP) - CAST( SYSDATE AS TIMESTAMP) ),12,8 ) TEMPO 
       ,count  (cd_triagem_atendimento) OVER ()QTD_TRIAGEM       
FROM TRIAGEM_ATENDIMENTO 
WHERE DH_REMOVIDO IS NULL
and cd_fila_senha in (8)
and cd_cor_referencia is null
AND CD_ESPECIALID IS NULL
and cd_atendimento is null
AND TRUNC(DH_PRE_ATENDIMENTO)= TO_DATE(SYSDATE, 'DD/MM/RRRR') 
)
GROUP BY QTD_TRIAGEM

--- DIRECIONADO
UNION ALL 


SELECT 'TRIAGEM - DIRECIONADO' TIPO 
      , QTD_TRIAGEM
      , Max (tempo) MAIOR_TEMPO_ESP  
FROM (
SELECT SUBSTR( (CAST(DH_PRE_ATENDIMENTO  AS TIMESTAMP) - CAST( SYSDATE AS TIMESTAMP) ),12,8 ) TEMPO 
       ,count  (cd_triagem_atendimento) OVER ()QTD_TRIAGEM       
FROM TRIAGEM_ATENDIMENTO 
WHERE DH_REMOVIDO IS NULL
and cd_fila_senha in (1)
and cd_cor_referencia is null
AND CD_ESPECIALID IS NULL
and cd_atendimento is null
AND TRUNC(DH_PRE_ATENDIMENTO)= TO_DATE(SYSDATE, 'DD/MM/RRRR') 
)
GROUP BY QTD_TRIAGEM
