--MAIOR TEMPO ESPERA TRIAGEM
SELECT DISTINCT
CASE 
WHEN ((SELECT Max(TO_CHAR(DH_PRE_ATENDIMENTO, 'HH24:MI')) 
AS MAIOR_TEMPO_TRIAGEM FROM TRIAGEM_ATENDIMENTO 
--WHERE CD_PACIENTE IS NULL 
--AND NM_PACIENTE IS NULL 
--WHERE DS_OBSERVACAO_REMOVIDO IS NULL ajustado 24/10/2021
WHERE DH_REMOVIDO IS NULL
and cd_fila_senha in (1,3,8)
and cd_cor_referencia is null
AND CD_ESPECIALID IS NULL
and cd_atendimento is null
AND TRUNC(DH_PRE_ATENDIMENTO)=TO_DATE(SYSDATE,'dd/mm/rrrr')) is null) 
THEN '--' 
ELSE
(SELECT TO_CHAR(24*60*(Max(SYSDATE-DH_PRE_ATENDIMENTO)),'999')||' '|| 'Min' 
AS MAIOR_TEMPO_TRIAGEM FROM TRIAGEM_ATENDIMENTO 
--WHERE CD_PACIENTE IS NULL 
--AND NM_PACIENTE IS NULL 
--WHERE DS_OBSERVACAO_REMOVIDO IS NULL
WHERE DH_REMOVIDO IS NULL
and cd_fila_senha in (1,3,8)
and cd_cor_referencia is null
AND CD_ESPECIALID IS NULL
and cd_atendimento is null
AND TRUNC(DH_PRE_ATENDIMENTO)=TO_DATE(SYSDATE, 'DD/MM/RRRR')) END 
AS MAIOR_TEMPO_TRIAGEM FROM TRIAGEM_ATENDIMENTO