--MAIOR TEMPO ESPERA CADASTRO---------------  
SELECT DISTINCT
CASE 
WHEN ((SELECT Max(TO_CHAR(A.DH_PRE_ATENDIMENTO_FIM, 'HH24:MI')) 
FROM TRIAGEM_ATENDIMENTO A
INNER JOIN ESPECIALID B ON A.CD_ESPECIALID=B.CD_ESPECIALID
WHERE A.DH_PRE_ATENDIMENTO_FIM is NOT NULL 
AND A.NM_PACIENTE IS NOT NULL 
AND A.CD_FILA_SENHA IN (1,3,8,11)
AND B.CD_ESPECIALID=36
AND A.cd_classificacao is not null 
AND A.cd_atendimento is null
AND A.DS_OBSERVACAO_REMOVIDO IS NULL
AND TRUNC(A.DH_PRE_ATENDIMENTO_FIM)=to_date(sysdate, 'dd/mm/rrrr')) IS NULL)
THEN '--' 
ELSE
(SELECT TO_CHAR(24*60*(MAX(SYSDATE-DH_PRE_ATENDIMENTO_FIM)),'999')||' '|| 'Min' AS MAIOR_TEMPO_CADASTRO
FROM TRIAGEM_ATENDIMENTO A
INNER JOIN ESPECIALID B ON A.CD_ESPECIALID=B.CD_ESPECIALID
WHERE A.DH_PRE_ATENDIMENTO_FIM is NOT NULL 
AND A.NM_PACIENTE IS NOT NULL 
 AND A.CD_FILA_SENHA IN (1,3,8,11)
AND B.CD_ESPECIALID=36
AND A.cd_classificacao is not null 
AND A.cd_atendimento is null
AND A.DS_OBSERVACAO_REMOVIDO IS NULL
AND TRUNC(A.DH_PRE_ATENDIMENTO_FIM)=to_date(sysdate, 'dd/mm/rrrr'))
END AS MAIOR_TEMPO
FROM TRIAGEM_ATENDIMENTO