SELECT * FROM (
SELECT  'REALIZADO' TIPO,
        To_Char(DT_REALIZACAO,'DD/MM/YYYY')AS DT_REALIZACAO, 
        ELETIVOS, 
        URGENTES, 
        TOTAL_MES
FROM
(
SELECT DT_REALIZACAO, COUNT(TIPO_ELE) ELETIVOS, COUNT(TIPO_URG) URGENTES, SUM(COUNT(TIPO_ELE)+COUNT(TIPO_URG)) OVER()TOTAL_MES
FROM
(
SELECT  CASE WHEN TP_CIRURGIAS = 'E' THEN 'ELETIVO' END TIPO_ELE
       ,CASE WHEN TP_CIRURGIAS IN ('U','M') THEN 'URGENCIA' END TIPO_URG
      ,trunc(AVISO_CIRURGIA.DT_REALIZACAO) DT_REALIZACAO   
FROM AVISO_CIRURGIA
WHERE TP_CIRURGIAS IN ('E','U','M')
AND TP_SITUACAO = 'R'  -- cirurgias realizadas 
AND trunc(AVISO_CIRURGIA.DT_REALIZACAO) between  trunc(sysdate,'MM') and SYSDATE 
ORDER BY 3 DESC
)
GROUP BY DT_REALIZACAO                 
ORDER BY 2 
)

UNION 

------ agendadas
SELECT  'PREVISTO' TIPO,
        To_Char(DT_PREVISAO,'DD/MM/YYYY')AS DT_REALIZACAO, 
        ELETIVOS, 
        URGENTES, 
        TOTAL_MES
FROM
(
SELECT DT_PREVISAO, COUNT(TIPO_ELE) ELETIVOS, COUNT(TIPO_URG) URGENTES, SUM(COUNT(TIPO_ELE)+COUNT(TIPO_URG)) OVER()TOTAL_MES
FROM
(
SELECT  CASE WHEN TP_CIRURGIAS = 'E' THEN 'ELETIVO' END TIPO_ELE
       ,CASE WHEN TP_CIRURGIAS IN ('U','M') THEN 'URGENCIA' END TIPO_URG
       ,trunc(AVISO_CIRURGIA.dt_prev_inter) DT_PREVISAO  
FROM AVISO_CIRURGIA
WHERE TP_CIRURGIAS IN ('E','U','M')
AND TP_SITUACAO = 'G' -- cirurgias agendadas 
AND trunc(AVISO_CIRURGIA.dt_prev_inter) BETWEEN  Trunc(SYSDATE + 1 ) AND ( SYSDATE ) + 3

ORDER BY 3 DESC
)
GROUP BY DT_PREVISAO                 
ORDER BY 2 
)
)ORDER BY 2 
