 --predicted_highs
 --alta hospitalar (alta administrativa)
 SELECT 'ALTA_HOSPITALAR' TIPO,
 COUNT(ATENDIME.CD_ATENDIMENTO) QTD_ALTAS_HOSPITALAR
 FROM DBAMV.ATENDIME,
 DBAMV.UNID_INT,
 DBAMV.LEITO,
 DBAMV.MOT_ALT
 WHERE ATENDIME.TP_ATENDIMENTO = 'I'
 AND ATENDIME.CD_LEITO = LEITO.CD_LEITO
 AND LEITO.CD_UNID_INT = UNID_INT.CD_UNID_INT
 AND ATENDIME.DT_ALTA IS NOT NULL  
 --AND ATENDIME.DT_ALTA = TRUNC(SYSDATE) --ALTA HOSPITALAR
 AND Trunc (ATENDIME.DT_ALTA) between trunc(sysdate)  and SYSDATE     
 AND ATENDIME.CD_MOT_ALT=MOT_ALT.CD_MOT_ALT
 AND UNID_INT.CD_UNID_INT NOT IN (5,19,22,1)
 AND MOT_ALT.TP_MOT_ALTA='A'
 AND ATENDIME.CD_MULTI_EMPRESA = 1

UNION ALL 
 --alta médica (saída real?)

 SELECT 'ALTA_MEDICA' TIPO,
 COUNT(ATENDIME.CD_ATENDIMENTO) QTD_ALTAS_HOSPITALAR
 FROM DBAMV.ATENDIME,
 DBAMV.UNID_INT,
 DBAMV.LEITO,
 DBAMV.MOT_ALT
 WHERE ATENDIME.TP_ATENDIMENTO = 'I'
 AND ATENDIME.CD_LEITO = LEITO.CD_LEITO
 AND LEITO.CD_UNID_INT = UNID_INT.CD_UNID_INT
 AND ATENDIME.dt_alta_medica IS NOT NULL  -- ALTA MEDICA    
 --AND ATENDIME.dt_alta_medica = TRUNC(SYSDATE)
 AND Trunc (ATENDIME.dt_alta_medica) between trunc(sysdate)  and SYSDATE  
 AND ATENDIME.CD_MOT_ALT=MOT_ALT.CD_MOT_ALT
 AND UNID_INT.CD_UNID_INT NOT IN (5,19,22,1)
 AND MOT_ALT.TP_MOT_ALTA='A'
 AND ATENDIME.CD_MULTI_EMPRESA = 1

UNION ALL 
 --altas previstas dia

SELECT 'ALTAS PREVISTAS DIA' TIPO,
COUNT(ATENDIME.CD_ATENDIMENTO) QTD_ALTAS_PREVISTAS
 FROM DBAMV.ATENDIME,
 DBAMV.UNID_INT,
 DBAMV.LEITO 
 WHERE ATENDIME.TP_ATENDIMENTO = 'I'
 AND ATENDIME.CD_LEITO = LEITO.CD_LEITO
 AND LEITO.CD_UNID_INT = UNID_INT.CD_UNID_INT            
 AND Trunc (ATENDIME.dt_prevista_alta)between trunc(sysdate)  and SYSDATE 
 --AND UNID_INT.CD_UNID_INT NOT IN (5,19,22,1)
 AND ATENDIME.CD_MULTI_EMPRESA = 1

 UNION ALL 
  --altas prvistas prox 3 dias

SELECT 'ALTAS PREV PROX 3DIAS' TIPO,
COUNT(ATENDIME.CD_ATENDIMENTO) QTD_ALTAS_PREVISTAS
 FROM DBAMV.ATENDIME,
 DBAMV.UNID_INT,
 DBAMV.LEITO 
 WHERE ATENDIME.TP_ATENDIMENTO = 'I'
 AND ATENDIME.CD_LEITO = LEITO.CD_LEITO
 AND LEITO.CD_UNID_INT = UNID_INT.CD_UNID_INT         
 AND Trunc (ATENDIME.dt_prevista_alta)between trunc(sysdate)  and SYSDATE + 2
 --AND UNID_INT.CD_UNID_INT NOT IN (5,19,22,1)
 AND ATENDIME.CD_MULTI_EMPRESA = 1

UNION ALL 
   --altas prvistas prox 8 dias

SELECT 'ALTAS PREV PROX 8DIAS' TIPO,
COUNT(ATENDIME.CD_ATENDIMENTO) QTD_ALTAS_PREVISTAS
 FROM DBAMV.ATENDIME,
 DBAMV.UNID_INT,
 DBAMV.LEITO 
 WHERE ATENDIME.TP_ATENDIMENTO = 'I'
 AND ATENDIME.CD_LEITO = LEITO.CD_LEITO
 AND LEITO.CD_UNID_INT = UNID_INT.CD_UNID_INT         
 AND Trunc (ATENDIME.dt_prevista_alta)between trunc(sysdate)  and SYSDATE + 7
 AND ATENDIME.CD_MULTI_EMPRESA = 1


 ------------------- ALTAS UPP (andra) -----------
 UNION ALL 
 --altas previstas dia UPP

SELECT 'ALTAS PREVISTAS UPP DIA' TIPO,
COUNT(ATENDIME.CD_ATENDIMENTO) QTD_ALTAS_PREVISTAS 
 FROM DBAMV.ATENDIME,
 DBAMV.UNID_INT,
 DBAMV.LEITO 
 WHERE ATENDIME.TP_ATENDIMENTO = 'I'
 AND ATENDIME.CD_LEITO = LEITO.CD_LEITO
 AND LEITO.CD_UNID_INT = UNID_INT.CD_UNID_INT            
 AND Trunc (ATENDIME.dt_prevista_alta)between trunc(sysdate)  and SYSDATE 
 AND UNID_INT.CD_UNID_INT IN (23,30) --UPP
 AND ATENDIME.CD_MULTI_EMPRESA = 1  

 UNION ALL 
  --altas prvistas prox 3 dias UPP

SELECT 'ALTAS PREV UPP PROX 3DIAS' TIPO,
COUNT(ATENDIME.CD_ATENDIMENTO) QTD_ALTAS_PREVISTAS
 FROM DBAMV.ATENDIME,
 DBAMV.UNID_INT,
 DBAMV.LEITO 
 WHERE ATENDIME.TP_ATENDIMENTO = 'I'
 AND ATENDIME.CD_LEITO = LEITO.CD_LEITO
 AND LEITO.CD_UNID_INT = UNID_INT.CD_UNID_INT         
 AND Trunc (ATENDIME.dt_prevista_alta)between trunc(sysdate)  and SYSDATE + 2
 AND UNID_INT.CD_UNID_INT IN (23,30) --UPP
 AND ATENDIME.CD_MULTI_EMPRESA = 1

UNION ALL 
   --altas prvistas prox 8 dias UPP

SELECT 'ALTAS PREV UPP PROX 8DIAS' TIPO,
       COUNT(ATENDIME.CD_ATENDIMENTO) QTD_ALTAS_PREVISTAS
     -- ,ds_unid_int
    --  ,ds_leito
 FROM DBAMV.ATENDIME,
 DBAMV.UNID_INT,
 DBAMV.LEITO 
 WHERE ATENDIME.TP_ATENDIMENTO = 'I'
 AND ATENDIME.CD_LEITO = LEITO.CD_LEITO
 AND LEITO.CD_UNID_INT = UNID_INT.CD_UNID_INT 
 AND UNID_INT.CD_UNID_INT IN (23,30) --UPP 
 --AND LEITO.DS_LEITO  LIKE '%UPP%'       
 AND Trunc (ATENDIME.dt_prevista_alta)between trunc(sysdate)  and SYSDATE + 7
 AND ATENDIME.CD_MULTI_EMPRESA = 1 

UNION ALL

-- internações prox 3 dias
SELECT 'INTERNACOES PREV PROX 3DIAS' TIPO
,Count  (cd_paciente)PREV_INTERNACAO
FROM (
SELECT RES_LEI.nm_paciente 
      ,RES_LEI.cd_paciente
      ,atendime.cd_atendimento
      ,RES_LEI.cd_leito 
      ,RES_LEI.dt_reserva
      ,RES_LEI.dt_prev_alta
      ,DT_PREV_INTERNACAO
      ,atendime.dt_alta
FROM DBAMV.RES_LEI
    ,DBAMV.ATENDIME
WHERE ATENDIME.cd_atendimento = RES_LEI.cd_atendimento
  AND atendime.dt_alta IS  NULL
  AND tp_atendimento = 'I'

  AND Trunc (DT_PREV_INTERNACAO) between trunc(sysdate) and SYSDATE + 2 
  ORDER BY DT_PREV_INTERNACAO
 )