SELECT
  CASE  WHEN tp_situacao = 'T' THEN 'ATENDIDO'
        WHEN tp_situacao IN ('U','L') THEN 'PREVISTO' ELSE '' END  TIPO,
  Count(CD_ORD_COM) QTD_ORDEM_COMPRAS,
  To_Char(Sum(VL_TOTAL)) VALOR_TOTAL
 FROM (
SELECT DISTINCT cd_ord_com,dt_prev_entrega, tp_situacao, VL_TOTAL  FROM (
SELECT ESTOQUE.CD_ESTOQUE
               ,ESTOQUE.DS_ESTOQUE
               ,ORD_COM.CD_ORD_COM
               ,ORD_COM.DT_PREV_ENTREGA
               ,ORD_COM.TP_SITUACAO
               ,FORNECEDOR.CD_FORNECEDOR
               ,FORNECEDOR.NM_FORNECEDOR
               ,ITORD_PRO.CD_PRODUTO
               ,ITORD_PRO.DT_CANCEL
               ,PRODUTO.ds_produto || DECODE(PRODUTO.ds_complemento, null,null,' ') || PRODUTO.ds_complemento || DECODE(PRODUTO.nr_referencia, null,null,' ') || PRODUTO.nr_referencia	ds_produto
               ,UNI_PRO.DS_UNIDADE
               ,(EST_PRO.QT_ESTOQUE_ATUAL / UNI_PRO.VL_FATOR) QT_ESTOQUE_ATUAL
               ,Nvl(ITORD_PRO.QT_COMPRADA,0) QT_COMPRADA
               ,Nvl(ITORD_PRO.QT_CANCELADA,0) QT_CANCELADA
               ,Nvl(ITORD_PRO.QT_RECEBIDA,0)  QT_RECEBIDA
               ,ORD_COM.VL_TOTAL
	,( Nvl(ITORD_PRO.QT_COMPRADA,0) - ( Nvl(ITORD_PRO.QT_RECEBIDA,0) + Nvl(ITORD_PRO.QT_CANCELADA,0))) QT_DIFERENCA
	,NVL(CD_ID_USUARIO_AUTORIZOU,USUARIO_AUTORIZADOR) USUARIO_AUTORIZADOR
  ,'N' EM_SERIE
,DT_AUTORIZACAO DT_AUTORIZACAO_N_SERIE
    FROM DBAMV.ESTOQUE
               ,DBAMV.ORD_COM
               ,DBAMV.ITORD_PRO
               ,DBAMV.PRODUTO
               ,DBAMV.UNI_PRO
               ,DBAMV.EST_PRO
               ,DBAMV.FORNECEDOR
 WHERE ESTOQUE.CD_ESTOQUE                 = ORD_COM.CD_ESTOQUE
       AND ESTOQUE.CD_MULTI_EMPRESA    = 1
       AND ORD_COM.CD_ORD_COM                = ITORD_PRO.CD_ORD_COM
       AND ITORD_PRO.CD_PRODUTO             = PRODUTO.CD_PRODUTO
       AND UNI_PRO.CD_UNI_PRO                    = ITORD_PRO.CD_UNI_PRO
       AND ESTOQUE.CD_ESTOQUE                 = EST_PRO.CD_ESTOQUE
       AND PRODUTO.CD_PRODUTO                = EST_PRO.CD_PRODUTO (+)
       AND FORNECEDOR. CD_FORNECEDOR = ORD_COM.CD_FORNECEDOR
       AND produto.sn_padronizado = 'N'
       AND ORD_COM.DT_PREV_ENTREGA BETWEEN To_Date(SYSDATE-180) AND To_Date(SYSDATE)
       AND NVL( ORD_COM.SN_CONSIGNADO_FATURA_DIRETA,'N' ) = 'N'
       AND ORD_COM.CD_ORD_COM NOT IN (SELECT AOC.CD_ORD_COM FROM DBAMV.AUTORIZADOR_ORDEM_COMPRA AOC WHERE AOC.CD_ORD_COM = ORD_COM.CD_ORD_COM)


UNION ALL

SELECT ESTOQUE.CD_ESTOQUE
               ,ESTOQUE.DS_ESTOQUE
               ,ORD_COM.CD_ORD_COM
               ,ORD_COM.DT_PREV_ENTREGA
               ,ORD_COM.TP_SITUACAO
               ,FORNECEDOR.CD_FORNECEDOR
               ,FORNECEDOR.NM_FORNECEDOR
               ,ITORD_PRO.CD_PRODUTO
               ,ITORD_PRO.DT_CANCEL
               ,PRODUTO.ds_produto || DECODE(PRODUTO.ds_complemento, null,null,' ') || PRODUTO.ds_complemento || DECODE(PRODUTO.nr_referencia, null,null,' ') || PRODUTO.nr_referencia	ds_produto
               ,UNI_PRO.DS_UNIDADE
               ,(EST_PRO.QT_ESTOQUE_ATUAL / UNI_PRO.VL_FATOR) QT_ESTOQUE_ATUAL
               ,Nvl(ITORD_PRO.QT_COMPRADA,0) QT_COMPRADA
               ,Nvl(ITORD_PRO.QT_CANCELADA,0) QT_CANCELADA
               ,Nvl(ITORD_PRO.QT_RECEBIDA,0)  QT_RECEBIDA
               ,ORD_COM.VL_TOTAL
	,( Nvl(ITORD_PRO.QT_COMPRADA,0) - ( Nvl(ITORD_PRO.QT_RECEBIDA,0) + Nvl(ITORD_PRO.QT_CANCELADA,0))) QT_DIFERENCA
	,NVL(CD_ID_USUARIO_AUTORIZOU,USUARIO_AUTORIZADOR) USUARIO_AUTORIZADOR
  ,'S' EM_SERIE
,DT_AUTORIZACAO DT_AUTORIZACAO_N_SERIE
    FROM DBAMV.ESTOQUE
               ,DBAMV.ORD_COM
               ,DBAMV.ITORD_PRO
               ,DBAMV.PRODUTO
               ,DBAMV.UNI_PRO
               ,DBAMV.EST_PRO
               ,DBAMV.FORNECEDOR
 WHERE ESTOQUE.CD_ESTOQUE                 = ORD_COM.CD_ESTOQUE
       AND ESTOQUE.CD_MULTI_EMPRESA    = 1
       AND ORD_COM.CD_ORD_COM                = ITORD_PRO.CD_ORD_COM
       AND ITORD_PRO.CD_PRODUTO             = PRODUTO.CD_PRODUTO
       AND UNI_PRO.CD_UNI_PRO                    = ITORD_PRO.CD_UNI_PRO
       AND ESTOQUE.CD_ESTOQUE                 = EST_PRO.CD_ESTOQUE
       AND PRODUTO.CD_PRODUTO                = EST_PRO.CD_PRODUTO (+)
       AND FORNECEDOR.CD_FORNECEDOR = ORD_COM.CD_FORNECEDOR
       AND ORD_COM.DT_PREV_ENTREGA BETWEEN To_Date(SYSDATE-180) AND To_Date(SYSDATE)
       AND NVL( ORD_COM.SN_CONSIGNADO_FATURA_DIRETA,'N' ) = 'N'
       AND produto.sn_padronizado = 'N'
       AND ORD_COM.CD_ORD_COM IN (SELECT AOC.CD_ORD_COM FROM DBAMV.AUTORIZADOR_ORDEM_COMPRA AOC WHERE AOC.CD_ORD_COM = ORD_COM.CD_ORD_COM)

ORDER BY DT_PREV_ENTREGA, cd_ord_com

)  WHERE tp_situacao in ('T','U','L')
 AND (TP_SITUACAO = 'T' AND dt_prev_entrega BETWEEN SYSDATE-30 AND SYSDATE)
 OR  (TP_SITUACAO IN ('U','L') AND dt_prev_entrega BETWEEN SYSDATE-180 AND SYSDATE)
ORDER BY DT_PREV_ENTREGA,
CD_ORD_COM )

GROUP BY  (CASE  WHEN tp_situacao = 'T' THEN 'ATENDIDO'
        WHEN tp_situacao IN ('U','L') THEN 'PREVISTO' ELSE '' END )




