--tempo real do cadastro
SELECT A.CD_COR_REFERENCIA ,
 COR.DS_REFERENCIA CLASSIFICACAO,
 FILA.DS_FILA FILA,
 count (*) AS EM_ESPERA_CADASTRO,
 TO_CHAR(24*60*(MAX(SYSDATE-DH_PRE_ATENDIMENTO_FIM)),'999') ||' '|| 'Min' AS MAIOR_TEMPO_CADASTRO,
 to_number(TO_CHAR(24*60*(MAX(SYSDATE-DH_PRE_ATENDIMENTO_FIM)),'999'))maior
FROM TRIAGEM_ATENDIMENTO A
INNER JOIN ESPECIALID B ON A.CD_ESPECIALID=B.CD_ESPECIALID
INNER JOIN COR_REFERENCIA COR ON A.CD_COR_REFERENCIA = COR.CD_COR_REFERENCIA
INNER JOIN FILA_SENHA FILA ON A.CD_FILA_SENHA = FILA.CD_FILA_SENHA
--INNER JOIN FILA_SENHA FL ON A.Cd_Fila_Senha = fl.cd_fila_senha
WHERE A.DH_PRE_ATENDIMENTO_FIM is NOT NULL 
AND A.CD_FILA_SENHA IN (1,3,8,11)
AND A.NM_PACIENTE IS NOT NULL 
AND B.CD_ESPECIALID=36
AND A.cd_classificacao is not null 
AND A.cd_atendimento is null
AND A.DS_OBSERVACAO_REMOVIDO IS NULL
AND TRUNC(A.DH_PRE_ATENDIMENTO_FIM)=to_date(sysdate, 'dd/mm/rrrr')
GROUP BY A.CD_COR_REFERENCIA, COR.DS_REFERENCIA,FILA.DS_FILA