SELECT nvl(ROUND((LOC.LEITO/(LTOTAL.LEITOT/100))),0)||'%' PERCENTAGEM_OCUPACAO FROM
(SELECT COUNT(L.CD_LEITO) LEITO
FROM  LEITO L , UNID_INT U
WHERE L.CD_UNID_INT = U.CD_UNID_INT
AND   U.TP_UNID_INT = 'I'
AND   L.TP_OCUPACAO IN ('O','I','A')
AND   L.SN_EXTRA = 'N'
AND  l.tp_situacao = 'A'
AND  L.cd_unid_int not in (5,22,19,1,21)) LOC,

(SELECT COUNT(L.CD_LEITO) LEITOT
FROM  LEITO L , UNID_INT U
WHERE L.CD_UNID_INT = U.CD_UNID_INT
AND   U.TP_UNID_INT = 'I'
AND   L.SN_EXTRA = 'N'
AND l.tp_situacao = 'A'
AND  L.cd_unid_int not in (5,22,19,1,21)) LTOTAL
