----- motivo da alta (geovanna)

SELECT

----------------------- HOMECARE
Nvl ((
SELECT Count(*) QTD_HOMECARE_UI
FROM(
SELECT
'MOTIVO DE ALTA HOMECARE UI' TIPO,
ATENDIME.CD_ATENDIMENTO,
ATENDIME.CD_MOT_ALT,
PACIENTE.NM_PACIENTE,
ATENDIME.DT_ALTA,
Count(CD_ATENDIMENTO) QTD_HOMECARE_UI


FROM
ATENDIME,
PACIENTE,
MOT_ALT,
LEITO

WHERE
     ATENDIME.CD_PACIENTE = PACIENTE.CD_PACIENTE
AND  ATENDIME.CD_MOT_ALT  = MOT_ALT.CD_MOT_ALT
AND  ATENDIME.CD_LEITO    = LEITO.CD_UNID_INT
AND  LEITO.CD_UNID_INT IN (37,28,23,8,9,10,11,12,13,40,15)-- UNIDADES DE INTERNÇAO UI
AND  ATENDIME.CD_MOT_ALT  = 44
--AND  ATENDIME.DT_ALTA  >= SYSDATE - 1
AND To_date(ATENDIME.HR_ALTA,'dd/mm/yyyy hh24:mi') BETWEEN To_Date (SYSDATE,'dd/mm/yyyy hh24:mi') AND To_Date (SYSDATE,'dd/mm/yyyy')

GROUP BY
ATENDIME.CD_ATENDIMENTO,
ATENDIME.CD_MOT_ALT,
PACIENTE.NM_PACIENTE,
ATENDIME.DT_ALTA
  )
) ,0) HOMECARE_UI,

Nvl (
(
SELECT Count(*) QTD_HOMECARE_UTI
FROM(SELECT
'MOTIVO DE ALTA HOMECARE UTI' TIPO,
ATENDIME.CD_ATENDIMENTO,
ATENDIME.CD_MOT_ALT,
PACIENTE.NM_PACIENTE,
ATENDIME.DT_ALTA,
Count(CD_ATENDIMENTO) QTD_HOMECARE_UTI

FROM
ATENDIME,
PACIENTE,
MOT_ALT,
LEITO

WHERE
     ATENDIME.CD_PACIENTE = PACIENTE.CD_PACIENTE
AND  ATENDIME.CD_MOT_ALT  = MOT_ALT.CD_MOT_ALT
AND  ATENDIME.CD_LEITO    = LEITO.CD_UNID_INT
AND  LEITO.CD_UNID_INT IN (38,3,25,7,26,27,31,34,16,30,45)-- UNIDADES DE INTERNÇAO UTI
AND  ATENDIME.CD_MOT_ALT  = 44
--AND  ATENDIME.DT_ALTA  >= SYSDATE - 1
AND To_date(ATENDIME.HR_ALTA,'dd/mm/yyyy hh24:mi') BETWEEN To_Date (SYSDATE,'dd/mm/yyyy hh24:mi') AND To_Date (SYSDATE,'dd/mm/yyyy')

GROUP BY
ATENDIME.CD_ATENDIMENTO,
ATENDIME.CD_MOT_ALT,
PACIENTE.NM_PACIENTE,
ATENDIME.DT_ALTA
 )
) ,0 ) HOMECARE_UTI,

-----------------------------------------

-------------------- OBITO

Nvl (
(
SELECT Count(*)  QTD_OBITO_UI
FROM(SELECT
'OBITO UI' TIPO,
ATENDIME.CD_ATENDIMENTO,
PACIENTE.NM_PACIENTE,
ATENDIME.DT_ALTA,
ATENDIME.SN_OBITO,
LEITO.DS_LEITO,
MOT_ALT.DS_MOT_ALT,
Count(CD_ATENDIMENTO) QTD_OBITO_UI

FROM
ATENDIME,
PACIENTE,
LEITO,
MOT_ALT

WHERE

      ATENDIME.CD_PACIENTE = PACIENTE.CD_PACIENTE
AND   ATENDIME.CD_LEITO    = LEITO.CD_LEITO
AND   LEITO.cd_unid_int IN (37,28,23,8,9,10,11,12,13,40,15)-- UNIDADES DE INTERNÇAO UI
AND   ATENDIME.CD_MOT_ALT  = MOT_ALT.CD_MOT_ALT
AND   MOT_ALT.CD_MOT_ALT IN (46,47)
AND   ATENDIME.SN_OBITO = 'S'
AND To_date(ATENDIME.DT_ALTA,'dd/mm/yyyy hh24:mi') BETWEEN To_Date (SYSDATE,'dd/mm/yyyy hh24:mi') AND To_Date (SYSDATE,'dd/mm/yyyy')
--AND ATENDIME.DT_ALTA >= SYSDATE - 1

GROUP BY
ATENDIME.CD_ATENDIMENTO,
PACIENTE.NM_PACIENTE,
ATENDIME.DT_ALTA,
ATENDIME.SN_OBITO,
LEITO.DS_LEITO,
MOT_ALT.DS_MOT_ALT
 )
) ,0 ) OBITO_UI ,

Nvl (
(
SELECT Count(*) QTD_OBITO_UTI
FROM(SELECT
'OBITO UTI' TIPO,
ATENDIME.CD_ATENDIMENTO,
PACIENTE.NM_PACIENTE,
ATENDIME.DT_ALTA,
ATENDIME.SN_OBITO,
LEITO.DS_LEITO,
MOT_ALT.DS_MOT_ALT,
Nvl(Count(CD_ATENDIMENTO),0) QTD_OBITO_UTI

FROM
ATENDIME,
PACIENTE,
LEITO,
MOT_ALT

WHERE

      ATENDIME.CD_PACIENTE = PACIENTE.CD_PACIENTE
AND   ATENDIME.CD_LEITO    = LEITO.CD_LEITO
AND   ATENDIME.CD_MOT_ALT  = MOT_ALT.CD_MOT_ALT
AND   MOT_ALT.CD_MOT_ALT IN (46,47)
AND   leito.cd_unid_int IN (38,3,25,7,26,31,34,16,30,45)-- UNIDADES DE INTERNÇAO UTI
AND   ATENDIME.SN_OBITO = 'S'
AND To_date(ATENDIME.DT_ALTA,'dd/mm/yyyy hh24:mi') BETWEEN To_Date (SYSDATE,'dd/mm/yyyy hh24:mi') AND To_Date (SYSDATE,'dd/mm/yyyy')
--AND ATENDIME.DT_ALTA >= SYSDATE - 1

GROUP BY
ATENDIME.CD_ATENDIMENTO,
PACIENTE.NM_PACIENTE,
ATENDIME.DT_ALTA,
ATENDIME.SN_OBITO,
LEITO.DS_LEITO,
MOT_ALT.DS_MOT_ALT
 )
) ,0 ) OBITO_UTI,

---------------------------------------------

------------------------ TRANSFERENCIA EXTERNA

Nvl(
(
SELECT Count(*) QTD_UI
FROM(SELECT
'TRANSFERENCIA PARA OUTRO HOSPITAL UI' TIPO,
ATENDIME.CD_ATENDIMENTO,
ATENDIME.CD_MOT_ALT,
PACIENTE.NM_PACIENTE,
ATENDIME.DT_ALTA,
Count(CD_ATENDIMENTO) QTD_UI

FROM
ATENDIME,
PACIENTE,
MOT_ALT,
LEITO

WHERE
     ATENDIME.CD_PACIENTE = PACIENTE.CD_PACIENTE
AND  ATENDIME.CD_MOT_ALT  = MOT_ALT.CD_MOT_ALT
AND  ATENDIME.CD_LEITO    = LEITO.CD_UNID_INT
AND  LEITO.CD_UNID_INT IN (37,28,23,8,9,10,11,12,13,40,15)-- UNIDADES DE INTERNÇAO UI
AND  ATENDIME.CD_MOT_ALT  = 15
--AND  ATENDIME.DT_ALTA  >= SYSDATE - 1
AND To_date(ATENDIME.HR_ALTA,'dd/mm/yyyy hh24:mi') BETWEEN To_Date (SYSDATE,'dd/mm/yyyy hh24:mi') AND To_Date (SYSDATE,'dd/mm/yyyy')

GROUP BY
ATENDIME.CD_ATENDIMENTO,
ATENDIME.CD_MOT_ALT,
PACIENTE.NM_PACIENTE,
ATENDIME.DT_ALTA
  )
) ,0 ) TRANSFERENCIA_EXTERNA_UI ,

Nvl (
(
SELECT Count(*) QTD_UTI
FROM(SELECT
'TRANSFERENCIA PARA OUTRO HOSPITAL UTI' TIPO,
ATENDIME.CD_ATENDIMENTO,
ATENDIME.CD_MOT_ALT,
PACIENTE.NM_PACIENTE,
ATENDIME.DT_ALTA,
Count(CD_ATENDIMENTO) QTD_UTI

FROM
ATENDIME,
PACIENTE,
MOT_ALT,
LEITO

WHERE
     ATENDIME.CD_PACIENTE = PACIENTE.CD_PACIENTE
AND  ATENDIME.CD_MOT_ALT  = MOT_ALT.CD_MOT_ALT
AND  ATENDIME.CD_LEITO    = LEITO.CD_UNID_INT
AND  LEITO.CD_UNID_INT IN (38,3,25,7,26,31,34,16,30,45)-- UNIDADES DE INTERNÇAO UTI
AND  ATENDIME.CD_MOT_ALT  = 15
--AND  ATENDIME.DT_ALTA  >= SYSDATE - 1
AND To_date(ATENDIME.HR_ALTA,'dd/mm/yyyy hh24:mi') BETWEEN To_Date (SYSDATE,'dd/mm/yyyy hh24:mi') AND To_Date (SYSDATE,'dd/mm/yyyy')

GROUP BY
ATENDIME.CD_ATENDIMENTO,
ATENDIME.CD_MOT_ALT,
PACIENTE.NM_PACIENTE,
ATENDIME.DT_ALTA
  )
) ,0 ) TRANSFERENCIA_EXTERNA_UTI,

-----------------------------------

--------------------------- ALTA HOSPITALAR

Nvl(
(
SELECT Count(*) QTD_ALTA
FROM(SELECT
'ALTA HOSPITALAR UI' TIPO,
ATENDIME.CD_ATENDIMENTO,
PACIENTE.NM_PACIENTE,
ATENDIME.HR_ATENDIMENTO,
ATENDIME.HR_ALTA,
Count(CD_ATENDIMENTO) QTD_ALTA

FROM
ATENDIME,
PACIENTE,
LEITO

WHERE

      ATENDIME.CD_PACIENTE = PACIENTE.CD_PACIENTE
AND   ATENDIME.CD_LEITO    = LEITO.CD_LEITO
AND   LEITO.cd_unid_int IN (37,28,23,8,9,10,11,12,13,40,15) -- UNIDADES DE INTERNÇAO UI
AND   ATENDIME.DT_ALTA IS NOT NULL
AND To_date(ATENDIME.HR_ALTA,'dd/mm/yyyy hh24:mi') BETWEEN To_Date (SYSDATE,'dd/mm/yyyy hh24:mi') AND To_Date (SYSDATE,'dd/mm/yyyy')

GROUP BY

CD_ATENDIMENTO,
NM_PACIENTE,
HR_ATENDIMENTO,
HR_ALTA
  )
) ,0) ALTA_HOSPITALAR_UI,

Nvl(
(
SELECT Count(*) QTD_ALTA
FROM(SELECT
'ALTA HOSPITALAR UTI' TIPO,
ATENDIME.CD_ATENDIMENTO,
PACIENTE.NM_PACIENTE,
ATENDIME.HR_ATENDIMENTO,
ATENDIME.HR_ALTA,
Count(CD_ATENDIMENTO) QTD_ALTA


FROM
ATENDIME,
PACIENTE,
LEITO

WHERE

      ATENDIME.CD_PACIENTE = PACIENTE.CD_PACIENTE
AND   ATENDIME.CD_LEITO    = LEITO.CD_LEITO
AND   leito.cd_unid_int IN (38,3,25,7,26,31,34,16,30,45) -- UNIDADES DE INTERNÇAO UTI
AND   ATENDIME.DT_ALTA IS NOT NULL
AND To_date(ATENDIME.HR_ALTA,'dd/mm/yyyy hh24:mi') BETWEEN To_Date (SYSDATE,'dd/mm/yyyy hh24:mi') AND To_Date (SYSDATE,'dd/mm/yyyy')
--AND ATENDIME.DT_ALTA >= SYSDATE - 1

GROUP BY

CD_ATENDIMENTO,
NM_PACIENTE,
HR_ATENDIMENTO,
HR_ALTA
 )
) ,0 ) ALTA_HOSPITALAR_UTI


FROM DUAL